### ISSUE TITLE
Ladybug inhibits Saxon update to v10.8

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/ibis-ladybug#133]
When updating the FrankFramework with Saxon version 10.8 (https://github.com/ibissource/iaf/pull/3291), the framework fails to start up with the message:
```
SEVERE: Exception sending context initialized event to listener instance of class [nl.nn.adapterframework.lifecycle.IbisApplicationInitializer]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reportXmlTransformer' defined in class path resource [springIbisTestTool.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'xsltResource' threw exception; nested exception is java.lang.NoSuchMethodError: net.sf.saxon.sxpath.XPathEvaluator: method <init>()V not found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1744)
```
Apparantly there is a conflict between Saxon 10 and 9

**Comment by nielsm5** [comment]
See `ReportXmlTransformer#setXslt(String)` `TransformerFactoryErrorListener` has been changed.
